name: Android APK Yapici Garantili

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodlari Al
        uses: actions/checkout@v4

      - name: Gerekli Programlari Kur
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev libffi6 autoconf libtool pkg-config zip unzip
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: APK Uret (Lisanslari Otomatik Onayla)
        run: yes | buildozer android debug

      - name: APK Dosyasini İndirmeye Hazirla
        uses: actions/upload-artifact@v4
        with:
          name: MP3-Indir-Pro-APK
          path: bin/*.apk
